
package wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://wsserver/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     * @throws Fault_Exception
     */
    @WebMethod(operationName = "Calculate")
    @WebResult(partName = "return")
    @Action(input = "http://wsserver/SoapService/CalculateRequest", output = "http://wsserver/SoapService/CalculateResponse", fault = {
        @FaultAction(className = Fault_Exception.class, value = "http://wsserver/SoapService/Calculate/Fault/Fault")
    })
    public float calculate(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Fault_Exception
    ;

}
